/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;

import Business.Employee.Employee;
import Business.Role.CustomerRole;
import Business.EcoSystem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Business.DB4OUtil.DB4OUtil;
import Business.Employee.EmployeeDirectory;
import Business.UserAccount.UserAccount;

/**
 *
 * @author negis,shimpim,rahul
 */
public class RegisterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterJPanel
     */
    JPanel userProcessContainer;
    private EcoSystem system;
    public RegisterJPanel(JPanel userProcessContainer,EcoSystem system) {
        initComponents();
        this.system = system;
        this.userProcessContainer =userProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        custlabel = new javax.swing.JLabel();
        passlabel = new javax.swing.JLabel();
        usernametxt = new javax.swing.JTextField();
        passtxt = new javax.swing.JTextField();
        createnewuser = new javax.swing.JButton();
        usernamelabel = new javax.swing.JLabel();
        custname = new javax.swing.JTextField();
        toplabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        custlabel.setBackground(new java.awt.Color(255, 255, 255));
        custlabel.setFont(new java.awt.Font("STSong", 1, 14)); // NOI18N
        custlabel.setForeground(new java.awt.Color(0, 51, 102));
        custlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        custlabel.setText("Customer Name:");
        custlabel.setOpaque(true);

        passlabel.setBackground(new java.awt.Color(255, 255, 255));
        passlabel.setFont(new java.awt.Font("STSong", 1, 14)); // NOI18N
        passlabel.setForeground(new java.awt.Color(0, 51, 102));
        passlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passlabel.setText("Password:");
        passlabel.setOpaque(true);

        usernametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametxtActionPerformed(evt);
            }
        });

        createnewuser.setBackground(new java.awt.Color(255, 255, 255));
        createnewuser.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        createnewuser.setForeground(new java.awt.Color(0, 51, 102));
        createnewuser.setText("Create");
        createnewuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createnewuserActionPerformed(evt);
            }
        });

        usernamelabel.setBackground(new java.awt.Color(255, 255, 255));
        usernamelabel.setFont(new java.awt.Font("STSong", 1, 14)); // NOI18N
        usernamelabel.setForeground(new java.awt.Color(0, 51, 102));
        usernamelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernamelabel.setText("UserAccount:");
        usernamelabel.setOpaque(true);

        toplabel.setBackground(new java.awt.Color(255, 255, 255));
        toplabel.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        toplabel.setForeground(new java.awt.Color(0, 51, 102));
        toplabel.setText("       New Customer Login");
        toplabel.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(toplabel, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(passlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(custlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(usernamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(passtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(custname, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(221, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createnewuser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(toplabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(custname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernamelabel)
                    .addComponent(usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(passlabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(passtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addComponent(createnewuser)
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createnewuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createnewuserActionPerformed
        // TODO add your handling code here:
        
        String name = custname.getText();
        EmployeeDirectory ed = system.getEmployeeDirectory();

        Employee inemployee = null;
        String userName =usernametxt.getText();
        String password = passtxt.getText();
      
      
         if(name.isEmpty()||userName.isEmpty()||password.isEmpty()){
                 JOptionPane.showMessageDialog(null, "Input Fields Empty!","Warning",JOptionPane.WARNING_MESSAGE);
                 return;
            }else{
            for(UserAccount ua: system.getUserAccountDirectory().getUserAccountList()){
                if(ua.getUsername().equals(userName)){
                    JOptionPane.showMessageDialog(null, "Customer already exist!","Warning",JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
            
            system.getUserAccountDirectory().createUserAccount(userName, password, inemployee, new CustomerRole());
            DB4OUtil.getInstance().storeSystem(system);
            JOptionPane.showMessageDialog(null, "Customer Register Successfully","Success",JOptionPane.PLAIN_MESSAGE);
            
            custname.setText("");
            usernametxt.setText("");
            passtxt.setText("");
            
        }  
        
        
    }//GEN-LAST:event_createnewuserActionPerformed

    private void usernametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernametxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createnewuser;
    private javax.swing.JLabel custlabel;
    private javax.swing.JTextField custname;
    private javax.swing.JLabel passlabel;
    private javax.swing.JTextField passtxt;
    private javax.swing.JLabel toplabel;
    private javax.swing.JLabel usernamelabel;
    private javax.swing.JTextField usernametxt;
    // End of variables declaration//GEN-END:variables
}
