/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PharmacyFinanceManagerRole;

import Business.DB4OUtil.DB4OUtil;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Request.Medicine;
import Business.Request.MoneyOrder;
import Business.Request.MoneyOrderDirectory;
import Business.Request.Order;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author negis,shimpim,rahul
 */
public class RequestFinancialPartnerMoneyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestFinancialPartnerMoneyJPanel
     */
    private JPanel userProcessContainer;
   // private Organization organization;
    private Enterprise enterprise;
    private EcoSystem system;
    private MoneyOrderDirectory moneyOrderDirectory;
    public RequestFinancialPartnerMoneyJPanel(JPanel userProcessContainer, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.system = system;
        this.moneyOrderDirectory = enterprise.getMoneyOrderDirectory();

        calTotalProfit();
        txtName.setText(enterprise.getName());
        txtPrice.setText(String.valueOf(enterprise.getTotalProfit()));
    }

    void calTotalProfit(){
        float sum = 0;
        for(Order order : system.getOrderDirectory().getOrderList()){
            if(order.getRName().equals(enterprise.getName())&&order.getStatus().equals("Finished")){
                sum += order.gettPrice();
            }
        }
        sum=(float) (sum*0.8);
        for(MoneyOrder moneyorder :moneyOrderDirectory.getMoneyOrderList()){
            if(moneyorder.getName().equals(enterprise.getName())&&moneyorder.getMoneyOrderStatus().equals("Approved")){
               sum-=moneyorder.getMoney();
        }}
        enterprise.setTotalProfit(sum);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        confirm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        mattx = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        back = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        confirm.setBackground(new java.awt.Color(255, 255, 255));
        confirm.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        confirm.setForeground(new java.awt.Color(0, 51, 102));
        confirm.setText("Confirm");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("STSong", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pharmacy Name:");
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("STSong", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Total Profit:");
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("STSong", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Money Request:");
        jLabel3.setOpaque(true);

        txtName.setFont(new java.awt.Font("STSong", 1, 14)); // NOI18N
        txtName.setEnabled(false);

        mattx.setFont(new java.awt.Font("STSong", 1, 14)); // NOI18N
        mattx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mattxActionPerformed(evt);
            }
        });

        txtPrice.setFont(new java.awt.Font("STSong", 1, 14)); // NOI18N
        txtPrice.setEnabled(false);
        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        back.setForeground(new java.awt.Color(0, 51, 102));
        back.setText("<< Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(111, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPrice)
                            .addComponent(txtName)
                            .addComponent(mattx, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(178, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(back)
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(mattx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(confirm)
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mattxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mattxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mattxActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        // TODO add your handling code here:
        if(mattx.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Money request text field empty!","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        else if(Float.parseFloat(mattx.getText())<0){
            JOptionPane.showMessageDialog(null, "Money request text field incorrect!","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        float x = enterprise.getTotalProfit();
        float money = Float.parseFloat(mattx.getText());
        if(money < x*2 ){
                  MoneyOrder moneyOrder = moneyOrderDirectory.createMoneyOrder();
                moneyOrder.setTotalProfit(enterprise.getTotalProfit());
                moneyOrder.setMoney(Float.parseFloat(mattx.getText()));
                moneyOrder.setMoneyOrderStatus("Processing");
                moneyOrder.setName(enterprise.getName());

    		
                JOptionPane.showMessageDialog(null, "Money request submitted successfully","Success",JOptionPane.PLAIN_MESSAGE);}
        
        else{
                
                JOptionPane.showMessageDialog(null, "Can't request money!","Warning",JOptionPane.WARNING_MESSAGE);
                 return;
                
            }
         mattx.setText("");
        DB4OUtil.getInstance().storeSystem(system);
    }//GEN-LAST:event_confirmActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        Component [] comps = userProcessContainer.getComponents();
        for(Component c : comps){
            if(c instanceof PharmacyFinanceManagerWorkAreaJPanel){
                PharmacyFinanceManagerWorkAreaJPanel panel = (PharmacyFinanceManagerWorkAreaJPanel) c;
                panel.populateMoneyOrderJTable();
            }
        }
    }//GEN-LAST:event_backActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton confirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField mattx;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
