/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DeliveryManRole;

import Business.DB4OUtil.DB4OUtil;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Request.Medicine;
import Business.Request.Order;
import Business.Request.OrderDirectory;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import UserInterface.PharmacyManagerRole.RequestModifyListJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author negis,shimpim,rahul
 */
public class DeliveryManWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DeliveryworkArea
     */
    
    private OrderDirectory orderDirectory;
    private JPanel userProcessContainer;
    
    
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem system;
    public DeliveryManWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise,EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.orderDirectory = enterprise.getOrderDirectory();
        this.enterprise = enterprise;
        this.userAccount = account;
        this.system = system;
        vallabel.setText(enterprise.getName());
        populateOrderTable();
        populateYourOrderTable();
    }

    
    private void populateOrderTable(){
        DefaultTableModel model = (DefaultTableModel) ordertable.getModel();
        model.setRowCount(0);
        Network network =null;
        for(Network n1 :system.getNetworkList()){
            for(Enterprise en: n1.getEnterpriseDirectory().getEnterpriseList()){
                if(en.getName().equals(enterprise.getName())){
                    network = n1;
                    break;
                }
            }
        }
       
        for (Order o : system.getOrderDirectory().getOrderList()){
            if(o.getStatus().equals("packed")&& network.getName().equals(o.getNetwork().getName())){
                Object[] row = new Object[4];
                row[0] = o;
                
                row[1] = o.getRName();
                row[2] = o.getAdd();
                row[3] = o.getStatus();
                model.addRow(row);
            }
            
        }
    }
     private void populateYourOrderTable(){
        DefaultTableModel model = (DefaultTableModel) orderinfotable.getModel();
        model.setRowCount(0);
        for (Order o : system.getOrderDirectory().getOrderList()){
            if(o.getStatus().equals("Deliverying")&&o.getDName().equals(userAccount.getUsername())){
                Object[] row = new Object[4];
                row[0] = o;
                
                row[1] = o.getRName();
                row[2] = o.getAdd();
                row[3] = o.getStatus();
                model.addRow(row);
            }
            
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ordertable = new javax.swing.JTable();
        vallabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        takeorder = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderinfotable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        completeorderbut = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setForeground(new java.awt.Color(0, 51, 102));

        ordertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Pharmacy", "Address", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ordertable);
        if (ordertable.getColumnModel().getColumnCount() > 0) {
            ordertable.getColumnModel().getColumn(1).setResizable(false);
            ordertable.getColumnModel().getColumn(2).setResizable(false);
            ordertable.getColumnModel().getColumn(3).setResizable(false);
        }

        vallabel.setBackground(new java.awt.Color(255, 255, 255));
        vallabel.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        vallabel.setForeground(new java.awt.Color(255, 255, 0));
        vallabel.setText("<value>");

        enterpriseLabel.setBackground(new java.awt.Color(255, 255, 255));
        enterpriseLabel.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(0, 51, 102));
        enterpriseLabel.setText("EnterPrise :");

        takeorder.setBackground(new java.awt.Color(255, 255, 255));
        takeorder.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        takeorder.setForeground(new java.awt.Color(0, 51, 102));
        takeorder.setText("Take the Order");
        takeorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takeorderActionPerformed(evt);
            }
        });

        jScrollPane2.setForeground(new java.awt.Color(0, 51, 102));

        orderinfotable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Pharmacy", "Address", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(orderinfotable);
        if (orderinfotable.getColumnModel().getColumnCount() > 0) {
            orderinfotable.getColumnModel().getColumn(1).setResizable(false);
            orderinfotable.getColumnModel().getColumn(2).setResizable(false);
            orderinfotable.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("STSong", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Prepared Orders");
        jLabel1.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("STSong", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Your Order Information");
        jLabel2.setOpaque(true);

        completeorderbut.setBackground(new java.awt.Color(255, 255, 255));
        completeorderbut.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        completeorderbut.setForeground(new java.awt.Color(0, 51, 102));
        completeorderbut.setText("Complete Order");
        completeorderbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeorderbutActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("Delivery Man Work Area");
        jLabel6.setOpaque(true);

        jSeparator1.setForeground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(enterpriseLabel)
                        .addGap(18, 18, 18)
                        .addComponent(vallabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(takeorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(completeorderbut, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLabel)
                    .addComponent(vallabel))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(takeorder))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(completeorderbut))
                .addContainerGap(169, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void takeorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takeorderActionPerformed
        // TODO add your handling code here:
        int selectedrow = ordertable.getSelectedRow();

        if(selectedrow <0)
        {
             JOptionPane.showMessageDialog(null,"Please select an order!","Warning",JOptionPane.WARNING_MESSAGE);
             return;
        }
        
       
        Order  order = (Order)ordertable.getValueAt(selectedrow,0);
            
            order.setStatus("Deliverying");
            order.setDName(userAccount.getUsername());
            
            
            JOptionPane.showMessageDialog(null, "Order assigned successfully","Warning",JOptionPane.WARNING_MESSAGE);
            populateOrderTable();
            populateYourOrderTable();
            DB4OUtil.getInstance().storeSystem(system);
    }//GEN-LAST:event_takeorderActionPerformed

    private void completeorderbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeorderbutActionPerformed
        // TODO add your handling code here:
        int selectedrow = orderinfotable.getSelectedRow();

        if(selectedrow <0)
        {
            JOptionPane.showMessageDialog(null, "Select a order!","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
       Order  vs = (Order)orderinfotable.getValueAt(selectedrow,0);
            
       vs.setStatus("Order Delivered");
  
       JOptionPane.showMessageDialog(null, "Order Delivered successfully!","Success",JOptionPane.PLAIN_MESSAGE);
       populateYourOrderTable();
       DB4OUtil.getInstance().storeSystem(system);
    }//GEN-LAST:event_completeorderbutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton completeorderbut;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable orderinfotable;
    private javax.swing.JTable ordertable;
    private javax.swing.JButton takeorder;
    private javax.swing.JLabel vallabel;
    // End of variables declaration//GEN-END:variables
}
