/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdministrativeRole;

import Business.DB4OUtil.DB4OUtil;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Role.Role;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author negis,shimpim,rahul
 */
public class PharmacyManageUserAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PharmacyManageUserAccountJPanel
     */
    private JPanel container;
    private Enterprise enterprise;
    private EcoSystem system;

    public PharmacyManageUserAccountJPanel(JPanel container, Enterprise enterprise,EcoSystem system) {
        initComponents();
        this.enterprise = enterprise;
        this.container = container;
        this.system = system;
        
        popOrganizationComboBox();
        popData();
    }

    public void popOrganizationComboBox() {
        emptypecombo.removeAllItems();

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            emptypecombo.addItem(organization);
        }
    }
    
    public void populateEmployeeComboBox(Organization organization){
        empnamecombo.removeAllItems();
        
        for (Employee employee : organization.getEmployeeDirectory().getEmployeeList()){
            empnamecombo.addItem(employee);
        }
    }
    
    private void populateRoleComboBox(Organization organization){
        rolecombo.removeAllItems();
        for (Role role : organization.getSupportedRole()){
            rolecombo.addItem(role);
        }
    }

    public void popData() {

        DefaultTableModel model = (DefaultTableModel) userJTable.getModel();

        model.setRowCount(0);

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            for (UserAccount useraccount : organization.getUserAccountDirectory().getUserAccountList()) {
                Object row[] = new Object[3];
                row[0] = organization.getName();
                row[1] = useraccount.getUsername();
                row[2] = useraccount.getPassword();
                ((DefaultTableModel) userJTable.getModel()).addRow(row);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        create = new javax.swing.JButton();
        emptypecombo = new javax.swing.JComboBox();
        uname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rolecombo = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        userJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        upass = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        empnamecombo = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        back.setForeground(new java.awt.Color(0, 51, 102));
        back.setText("<< Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 100, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("STSong", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Employee Type");
        jLabel5.setOpaque(true);
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 100, -1));

        create.setBackground(new java.awt.Color(255, 255, 255));
        create.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        create.setForeground(new java.awt.Color(0, 51, 102));
        create.setText("Create");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 510, 150, -1));

        emptypecombo.setFont(new java.awt.Font("STSong", 1, 14)); // NOI18N
        emptypecombo.setForeground(new java.awt.Color(0, 51, 102));
        emptypecombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        emptypecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emptypecomboActionPerformed(evt);
            }
        });
        add(emptypecombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 146, -1));

        uname.setFont(new java.awt.Font("STSong", 1, 14)); // NOI18N
        uname.setForeground(new java.awt.Color(0, 51, 102));
        add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 146, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("STSong", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Role");
        jLabel4.setOpaque(true);
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 50, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("STSong", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("User Name");
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 130, -1));

        rolecombo.setFont(new java.awt.Font("STSong", 1, 14)); // NOI18N
        rolecombo.setForeground(new java.awt.Color(0, 51, 102));
        rolecombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        rolecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolecomboActionPerformed(evt);
            }
        });
        add(rolecombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, 146, -1));

        userJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee Type", "User ID", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(userJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 666, 179));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("STSong", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Password");
        jLabel2.setOpaque(true);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 130, -1));

        upass.setFont(new java.awt.Font("STSong", 1, 14)); // NOI18N
        upass.setForeground(new java.awt.Color(0, 51, 102));
        add(upass, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, 146, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("STSong", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Employee Name");
        jLabel3.setOpaque(true);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 120, -1));

        empnamecombo.setFont(new java.awt.Font("STSong", 1, 14)); // NOI18N
        empnamecombo.setForeground(new java.awt.Color(0, 51, 102));
        empnamecombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(empnamecombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 146, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("User Management");
        jLabel6.setOpaque(true);
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 210, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
         String userName = uname.getText();
        String password = upass.getText();
        Organization organization = (Organization) emptypecombo.getSelectedItem();
        Employee employee = (Employee) empnamecombo.getSelectedItem();
        Role role = (Role) rolecombo.getSelectedItem();

        if(userName.isEmpty()||password.isEmpty()){
            JOptionPane.showMessageDialog(null, "Username/ Password field empty!","Warning",JOptionPane.WARNING_MESSAGE);
            return;
            
        }
        
            for(UserAccount ua:organization.getUserAccountDirectory().getUserAccountList()){
                if(ua.getUsername().equals(userName)){
                    JOptionPane.showMessageDialog(null, "User account already exist!","Warning",JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
          
                organization.getUserAccountDirectory().createUserAccount(userName, password, employee, role);
                popData();
                DB4OUtil.getInstance().storeSystem(system);
                 JOptionPane.showMessageDialog(null, "User created successfully","Success",JOptionPane.PLAIN_MESSAGE);
                uname.setText("");
                upass.setText("");
                
        
    }//GEN-LAST:event_createActionPerformed

    private void emptypecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emptypecomboActionPerformed
        Organization organization = (Organization) emptypecombo.getSelectedItem();
        if (organization != null){
            populateEmployeeComboBox(organization);
            populateRoleComboBox(organization);
        }
    }//GEN-LAST:event_emptypecomboActionPerformed

    private void rolecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolecomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rolecomboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton create;
    private javax.swing.JComboBox empnamecombo;
    private javax.swing.JComboBox emptypecombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox rolecombo;
    private javax.swing.JTextField uname;
    private javax.swing.JTextField upass;
    private javax.swing.JTable userJTable;
    // End of variables declaration//GEN-END:variables
}
